"use client";

import { useEffect, useState } from "react";
import KpiCard from "../../components/KpiCard";
import { formatPercent } from "../../dashboard/format";
import { useAuthenticatedFetch } from "../../hooks/useAuthenticatedFetch";

const summaryDefaults = {
  sales: 0,
  clicks: 0,
  addedToCart: 0,
  conversionRate: 0,
  impressions: 0,
  conversions: 0,
  dailySeries: [],
  topProducts: [],
};

const breakdownItems = [
  "Related Products",
  "Frequently Bought",
  "Inspired By Your Views",
  "New Frequently Bought Bundle Discount",
  "Recently Viewed Products",
  "Recommended Products",
  "Products Purchased Before",
  "Recommendations based on past purchase",
  "Top Selling Products",
  "Trending Products",
  "New Arrivals",
  "Featured Collections",
  "AI Powered Recommendations",
];

export default function AnalyticsPage() {
  const { apiFetch, isReady } = useAuthenticatedFetch();

  const [summary, setSummary] = useState(summaryDefaults);
  const [events, setEvents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    if (!isReady || !apiFetch) return;

    let mounted = true;

    const load = async () => {
      try {
        setLoading(true);
        setError("");

        const summaryData = await apiFetch("/analytics/summary?days=30");
        const eventData = await apiFetch("/analytics/events?limit=30");

        if (!mounted) return;

        setSummary({ ...summaryDefaults, ...(summaryData || {}) });
        setEvents(eventData || []);
      } catch (err) {
        if (!mounted) return;

        console.error("Analytics error:", err);
        setError(err.message || "Unable to load analytics.");
      } finally {
        if (mounted) setLoading(false);
      }
    };

    load();

    return () => {
      mounted = false;
    };
  }, [apiFetch, isReady]);

  const salesSeries = summary.dailySeries?.length ? summary.dailySeries : [0];
  const maxSeriesValue = Math.max(...salesSeries, 1);

  return (
    <div className="page-section analytics-page">
      <div className="surface analytics-header-card">
        <div>
          <p className="overline">Sales Generated By Wiser</p>
          <h1>Analytics</h1>
        </div>
      </div>

      <div className="analytics-kpi-grid">
        <KpiCard title="Wiser Generated Sales" value={`Rs ${summary.sales.toLocaleString()}`} subtitle="Last 30 days" />
        <KpiCard title="Total Clicks" value={summary.clicks} subtitle="Clicks on widgets" />
        <KpiCard title="Added To Cart" value={summary.addedToCart} subtitle="Products added from upsells" />
        <KpiCard title="Conversion Rate" value={formatPercent(summary.conversionRate)} subtitle="Clicks to conversions" />
      </div>

      <div className="analytics-chart-panel surface">
        <div className="analytics-chart-header">
          <div>
            <h2>Monthly Sales Overview</h2>
            <p className="small">Last 30 days</p>
          </div>
          <div className="analytics-switch-group">
            <button className="button-link small active">Widgets</button>
            <button className="button-link small">Pages</button>
          </div>
        </div>

        <div className="analytics-chart">
          <div className="analytics-chart-grid">
            {salesSeries.map((bar, index) => (
              <div
                key={index}
                className="analytics-chart-bar"
                style={{ height: `${Math.max((bar / maxSeriesValue) * 100, 6)}%` }}
              />
            ))}
          </div>
          <div className="analytics-chart-legend">
            {Array.from({ length: 5 }).map((_, index) => (
              <span key={index}>{index * 5}k</span>
            ))}
          </div>
        </div>
      </div>

      <div className="analytics-breakdown-grid">
        {breakdownItems.map((item) => (
          <div key={item} className="surface analytics-breakdown-card">
            <span className="small">{item}</span>
            <strong>₹0.00</strong>
          </div>
        ))}
      </div>

      <div className="surface analytics-products-card">
        <div className="analytics-products-header">
          <div>
            <h2>Top Performing Products</h2>
            <p className="small">Top Performing Product Based On Sales</p>
          </div>
          <button className="button-link small">Show</button>
        </div>
        <div className="analytics-products-grid">
          {(summary.topProducts?.length
            ? summary.topProducts
            : Array.from({ length: 4 }).map((_, index) => ({
                productId: `placeholder-${index}`,
                title: `Product ${index + 1}`,
                sales: 0,
                conversions: 0,
              }))).map((product) => (
            <div key={product.productId} className="analytics-product-item">
              <div>
                <strong>{product.title}</strong>
                <p className="small">Rs {Number(product.sales || 0).toFixed(2)}</p>
              </div>
              <span className="small">{product.conversions || 0} conversions</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
